# Generated by Django 4.1.5 on 2023-01-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel_attack", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="correct_answer",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="panel",
            name="question",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="panel",
            name="wrong_answer_1",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="panel",
            name="wrong_answer_2",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="panel",
            name="wrong_answer_3",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
