# Generated by Django 4.1.5 on 2023-01-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel_attack", "0002_panel_correct_answer_panel_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="col",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="panel",
            name="row",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
