# Generated by Django 5.0.3 on 2026-02-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_attack', '0003_panel_col_panel_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='image',
            field=models.CharField(blank=True, help_text="Optional filename in static/images/questions/ (e.g. 'eiffel.jpg')", max_length=200, null=True),
        ),
    ]
